import pygame

# Display
WINDOW_FRACTION = 0.5
FPS = 60
BACKGROUND_COLOR = (30, 30, 50)
GROUND_COLOR = (80, 160, 80)
GROUND_Y_FRACTION = 0.85
WINDOW_TITLE = "Action Game"

# Character
CHAR_COLOR = (240, 240, 240)
CHAR_LINE_WIDTH = 3
HEAD_RADIUS = 12
TORSO_LENGTH = 38
ARM_LENGTH = 22
LEG_LENGTH = 30

# Physics
GRAVITY = 1400
JUMP_VELOCITY = -520
MOVE_SPEED = 250

# Animation
WALK_CYCLE_PERIOD = 0.3
SWING_DURATION = 0.3
SWING_ARC_START = 150
SWING_ARC_END = 30

# Keys
KEY_LEFT = pygame.K_LEFT
KEY_RIGHT = pygame.K_RIGHT
KEY_JUMP = pygame.K_d
KEY_SWING = pygame.K_a
KEY_CROUCH = pygame.K_s
